### ISSUE TITLE
每次启服务器都会新增一个root

### ISSUE THREAD

**Issue by Charles8864** [fuyouawa/MMORPG#1]
每次启动服务器会报这个：
数据库“MMORPG”中的“user”表不存在，已自动创建，并添加一个管理员账号（账号=root，密码=1234567890）
然后表里多一个root账号
![image](https://github.com/user-attachments/assets/d674cb0d-f463-4bab-a628-dc3957ae066f)

**Comment by Charles8864** [comment]
exists = FreeSql.DbFirst.GetTablesByDatabase(DbConfig.DbName).Exists(t => t.Name == "user");
这里把GetTablesByDatabase("user")改成GetTablesByDatabase(DbConfig.DbName)了，不知道对吗？大佬

**Comment by Charles8864** [comment]
![image](https://github.com/user-attachments/assets/861288ce-8d92-48ff-8eda-c35cfbeb3500)
加了2个测试账号，但是无法登录哦。请问应该如何添加呢？

**Comment by arlozen** [comment]
测试账号无法登录是由于账号密码有长度限制，账号需要4-12个字符，密码需要8-16字符，文档里倒是也忘记写了
数据库的问题我明天看看

**Comment by arlozen** [comment]
好了，这回没问题了，客户端也新增了通知框，一些信息会以通知框的形式在右上角弹出来
